### ISSUE TITLE
Server running - How to add the bot to my WhatsApp?

### ISSUE THREAD

**Issue by joelwmale** [KarimJedda/whatsappcli#1]
I have the server running, however I can't like... add my bot? I have the number (using my girlfriends mobile number) added as a contact, but nothing seems to be working.

The server is definitely running. It says Server started ####### then nothing, also lists the correct mobile number, but can't find any way to add the bot :(

**Comment by KarimJedda** [comment]
Hi Joel, I answered on Medium, check it out and get back to me. 
Cheers,

**Comment by Pechi77** [comment]
medium link pls ?
