### ISSUE TITLE
yowsup.layers

### ISSUE THREAD

**Issue by peppeska** [KarimJedda/whatsappcli#3]
Hi,
after run **python src/server.py**
I recive:

```
raceback (most recent call last):
  File "src/server.py", line 1, in <module>
    from yowsup.layers import YowLayerEvent, YowParallelLayer
ImportError: No module named yowsup.layers
```

**Comment by KarimJedda** [comment]
Hi,

it looks like your python is not finding yowsup. 
Are you in a virtual environment?
Have you installed all the requirements in the opt/ folder?

**Comment by peppeska** [comment]
Hi,
I install ypwsup by pip

**Comment by rodgomesc** [comment]
use pip install -U yowsup2

Peppeska notifications@github.com escreveu no dia qui, 22/10/2015 às
14:04:

**Comment by peppeska** [comment]
oh.. now i will test it!

**Comment by peppeska** [comment]
ops...

```
Traceback (most recent call last):
  File "src/server.py", line 13, in <module>
    from router import RouteLayer
  File "/home/peppeska/Scaricati/whatsappcli/src/router.py", line 12, in <module>
    from routes import MediaViews
  File "/home/peppeska/Scaricati/whatsappcli/src/routes.py", line 2, in <module>
    from src.utils.memReport import memReport
ImportError: No module named src.utils.memReport
```

**Comment by hadipramono** [comment]
Try this 
1. export PYTHONPATH="$PYTHONPATH:$HOME/.python"
2. ln -s /home/user/work/project/foo ~/.python/

Reference: http://stackoverflow.com/questions/2325923/how-to-fix-importerror-no-module-named-error-in-python

**Comment by peppeska** [comment]
ok...
now it work.
Archlinux default python version is 3.0 
so i try to make different link to /usr/bin/python2 -> /usb/bin/python

and now it work

**Comment by satishkkk** [comment]
hey peppeska 
I am newbie to python and I got the same error as you get earlier!

Traceback (most recent call last):
  File "src/server.py", line 13, in <module>
    from router import RouteLayer
  File "/home/peppeska/Scaricati/whatsappcli/src/router.py", line 12, in <module>
    from routes import MediaViews
  File "/home/peppeska/Scaricati/whatsappcli/src/routes.py", line 2, in <module>
    from src.utils.memReport import memReport
ImportError: No module named src.utils.memReport 

I tried  this as suggest by hadipramono 
ln -s /home/satish/Desktop/whatsappcli-master/src router.py
but I get this error
ln: failed to create symbolic link ‘router.py’: File exists

can you please help me out to resolve this error
