### ISSUE TITLE
How can  install it on an arm like the raspberry?

### ISSUE THREAD

**Issue by ghost** [KarimJedda/whatsappcli#4]
Please give a receipt

**Comment by KarimJedda** [comment]
Nothing easier than that, there you go: http://www.instructables.com/id/WhatsApp-on-Raspberry-Pi/

**Comment by ghost** [comment]
cool! It works! THX

**Comment by KarimJedda** [comment]
Glad it helped dude, tell me if you do something cool with it, I am looking for new projects.
