### ISSUE TITLE
No valid sessionsBad Mac!

### ISSUE THREAD

**Issue by hadipramono** [KarimJedda/whatsappcli#5]
Hi, I am very happy because I found the way to communicate with whatsapp.
Yesterday, I install/run this project, the phone number can be used as "the bot".
But today I have problem, my server have an error "No valid sessionsBad Mac!"
Any solution?

Below is probelm:
_layer.py_  [ERROR][2015-10-23 15:42:17,650] No valid sessionsBad Mac!
_layer.py_  [ERROR][2015-10-23 15:42:17,665] No valid sessionsBad Mac!
_layer.py_  [ERROR][2015-10-23 15:42:17,679] No valid sessionsBad Mac!
_layer.py_  [ERROR][2015-10-23 15:42:17,694] No valid sessionsBad Mac!
_layer.py_  [ERROR][2015-10-23 15:42:17,709] No valid sessionsBad Mac!
_layer.py_  [ERROR][2015-10-23 15:42:17,724] No valid sessionsBad Mac!

**Comment by KarimJedda** [comment]
Hi there,

try to delete the folder in ~/.yowsup and restarting?
Keep me posted, I got this error sometimes too.

**Comment by hadipramono** [comment]
Ok thanks...
Solved the problem... :-)

**Comment by KarimJedda** [comment]
Sweet stuff! :+1: I hope you're having fun so far :)
